First Commit. First try.
cuttiecat/java-explore-with-me pull request #3
Opened 2023-09-29 11:20 UTC by cuttiecat

(c) hallelujah
Стало плохо от объёма..

2023-09-29 11:39 UTC, cuttiecat commented
Не понимаю в чём ошибка. Опять проблемы с Maven, которые решаются с помощью магии только..

2023-09-29 15:54 UTC, EugeneLenkevich requested changes
Привет, Светлана! Спасибо за PR.

Отличная работа! :)
Только тесты упали, их бы поднять

Посмотри ка вот этот момент, у тебя используется mapstruct и я вижу два  интерфейса, предположу что тот что Impl возможно лишний. Плюс библиотека будет для интерфейса генерировать реализацию как раз с таким с префиксом, не может ли быть тут конфликт, посмотри, пожалуйста

![image](https://github.com/cuttiecat/java-explore-with-me/assets/109306643/098acf8f-d1d0-4575-b223-414aabff1a7f)

2023-09-29 15:54 UTC, EugeneLenkevich commented on stats-service/stats-server/src/main/java/ru/practicum/stats_server/controller/StatsController.java
> +        if (start.isAfter(end)) {
Эту проверку наверно лучше в сервис опустить, сервис же могут дернуть и из другого места, пусть поведение везде будет одинаковым :)

2023-09-30 09:50 UTC, cuttiecat commented
> Привет, Светлана! Спасибо за PR.
> 
> Отличная работа! :) Только тесты упали, их бы поднять
> 
> Посмотри ка вот этот момент, у тебя используется mapstruct и я вижу два интерфейса, предположу что тот что Impl возможно лишний. Плюс библиотека будет для интерфейса генерировать реализацию как раз с таким с префиксом, не может ли быть тут конфликт, посмотри, пожалуйста
> 
> ![image](https://user-images.githubusercontent.com/109306643/271655661-098acf8f-d1d0-4575-b223-414aabff1a7f.png)

![image](https://github.com/cuttiecat/java-explore-with-me/assets/119683620/cafb8c78-5743-4661-a4d8-4a943ad30be7)
 Не получилось после исправления та же ошибка. Не понимаю, как её исправить...

2023-10-01 11:01 UTC, EugeneLenkevich commented
> ![image](https://user-images.githubusercontent.com/119683620/271766360-cafb8c78-5743-4661-a4d8-4a943ad30be7.png) Не получилось после исправления та же ошибка. Не понимаю, как её исправить...

глянул на тест, там замокан маппер, который производит преобразование. самое простое решение - это сделать как на скрине. А, вообще, в таких случаях надо поднимать бин маппера тоже, иначе мы тестируем моки, а не реальную логику :)

![image](https://github.com/cuttiecat/java-explore-with-me/assets/109306643/cd941e20-0775-473c-9d71-7df53b5e55d1)

2023-10-01 13:34 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо.
Строчку закомментрованную только лучше почикать, не оставлять :)

2023-10-03 15:31 UTC, merged