Main svc
cuttiecat/java-explore-with-me pull request #5
Opened 2023-10-03 19:36 UTC by cuttiecat

Удачи мне и вам легкой проверки!

2023-10-04 16:26 UTC, cuttiecat commented
Не понимаю, что делать с этими тестами :(
Там не получается исправить их. Ну или я гусеничка глупая..

2023-10-04 19:06 UTC, EugeneLenkevich commented
> Не понимаю, что делать с этими тестами :( Там не получается исправить их. Ну или я гусеничка глупая..

Судя по всему дело вот в чем
![image](https://github.com/cuttiecat/java-explore-with-me/assets/109306643/8cb11901-e49d-446e-874e-f5fc49b0e0e9)

Мы делаем маппер моком, но тут есть особенность - map-struct сам генерирует код реализации маппера (CategoryMapperImpl)

У нас есть два варианта починить тесты.
1. работать с моком, но вместо .thenCallRealMethod(); вызывать .thenReturn как в строке 175
2. не делать из маппера мок, а поднимать его как бин при старте теста, вот ссылочка :)

https://stackoverflow.com/questions/45275382/how-to-write-junit-test-for-mapstruct-abstract-mapper-injected-via-spring

2023-10-04 19:07 UTC, EugeneLenkevich requested changes
.

2023-10-08 23:11 UTC, cuttiecat commented
Исправила ошибки в мокито, теперь это. Не понимаю, как их исправить, и куда лезть. уже 2 день мучаюсь..

2023-10-09 05:20 UTC, EugeneLenkevich commented
> Исправила ошибки в мокито, теперь это. Не понимаю, как их исправить, и куда лезть. уже 2 день мучаюсь..

Привет!
Сам проект собирается, то есть наши тесты починены и проходят, но тут уже падают автотесты, которые проверяют api. Это лучше у наставника спросить, наставник гораздо быстрее ответит :)

![image](https://github.com/cuttiecat/java-explore-with-me/assets/109306643/a221d804-4eec-4682-a482-349cf637e543)

2023-10-09 05:20 UTC, EugeneLenkevich requested changes
.

2023-10-09 15:04 UTC, EugeneLenkevich approved these changes
Ух, целый триллер :D
Но главное все получилось, ты молодец, спасибо!

А в целом... ну вот тесты они такие тесты, он и иногда выкидывают разные фортеля  :)

2023-10-09 15:07 UTC, merged