Final Final.
cuttiecat/java-explore-with-me pull request #6
Opened 2023-10-09 19:05 UTC by cuttiecat

Ещё раз удачной проверки! 
В любом случае, спасибо за все ревью! :)

2023-10-10 04:55 UTC, EugeneLenkevich requested changes
Привет, Светлана! Спасибо за PR.

Отличная работа! :)
Как последний штришок давай поработаем с логированием. Это очень важно будет потом, когда придеться разбираться почему наше приложение не работает так как положено. Достаточно перенести наши логи на уровень сервисов, добавить входящие параметры, но, если есть желание, то можно прикрутить логирование http-запросов, в принципе это не долго но, в целом, интересно и полезно посмотреть в каком именно виде приходят эти запросы, заголовки, параметры и  пр  :)

2023-10-10 04:55 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/comment/controller/AdminCommentController.java
> +        log.info("Получен запрос GET на получение комментария по id.");
`log.info("Получен запрос GET на получение комментария по id = {}", commentId);`

Логи нам помогут потом, во время эксплуатации приложения, разбираться в случае возникновения какие то непонятных ситуаций, потому лучше всегда давать больше отладочной информации, такой как  входящие параметры.

Мне кажется что тут стоит разобраться мы хотим залогировать: если мы хотим залогировать сами бизнес-операции, то стоит перенести логирование на уровень сервиса, так как это его обязанности (допустим метод сервиса вызвал не контроллер, а задача по расписанию, тогда вызов залогирован тогда не будет), а вот если хотим залогировать http-запросы, то тут есть пара моментов а) эти данные могут сильно забивать логи, потому лучше сделать уровень логированитя - log.debug(...) для них. Далее, если нам надо именно http-запросы, то данных в таком логе недостаточно, в запросе как минимум есть еще заголовки и пр
То есть, надо разобраться что именно мы тут хотим логировать и принять соответствующее решение, иначе просто логи неинформативные будут :)

PS
для логирования http-запросов можешь вот это попробовать, если желание будет
https://github.com/zalando/logbook
как непосредственно прикрутить
https://errorsfixing.com/how-to-instantiate-logbook-in-spring-boot-app/

2023-10-10 04:55 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/comment/controller/PublicCommentController.java
> +        log.info("Получен GET-запрос на получение всех комментариев для события с id.", eventId);
log.info("Получен GET-запрос на получение всех комментариев для события с id = {}", eventId);

2023-10-10 04:55 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/comment/service/CommentServiceImpl.java
> +        User user = userService.checkUserExistAndGet(userId);
На самом деле вот тут бы то логирование сделать (только без указания http-методов), сервисы могут дергать не обязательно контроллеры, а те же другие сервисы, например. И, тогда, эти операции не будут залогированы, потом, в случае какого то инцидента, мы не увидим по логу что реально в коде происходило :)

2023-10-11 17:36 UTC, cuttiecat commented on ewm-service/src/main/java/ru/practicum/comment/controller/AdminCommentController.java
> +        log.info("Получен запрос GET на получение комментария по id.");
Решила сделать по-простому..

2023-10-11 18:55 UTC, EugeneLenkevich approved these changes
Привет, спасибо за доработку, ПР висит и не обновляется, смотрю по истории гита. В целом да, все верно, только по всем контроллерам перенести логи, но это ладно, простая механическая работа, главное в целом все верно, спасибо :)

2023-10-11 19:00 UTC, cuttiecat commented
> Привет, спасибо за доработку, ПР висит и не обновляется, смотрю по истории гита. В целом да, все верно, только по всем контроллерам перенести логи, но это ладно, простая механическая работа, главное в целом все верно, спасибо :)

Вам спасибо за такое длинное путешествие. Действительно было интересно с вами работать!

2023-10-12 08:14 UTC, merged